import test from 'node:test';
import assert from 'node:assert/strict';
import {createContract,recordInspection,compareRental} from '../src/lib/rental';
import {importLocations} from '../src/lib/tracking';
import {applyTelemetry} from '../src/lib/telemetry';
import {csv} from '../src/lib/export';
import {mockVehicles} from '../src/data/mockFleet';
import type {InspectionRecord,RentalContract} from '../src/types';
const contract:RentalContract={id:'TEST-1',renterName:'Test renter',startDate:'2026-01-01T00:00:00Z',expectedReturnDate:'2026-02-01T00:00:00Z',dailyRate:150,status:'draft'};
function vehicle(){const v=structuredClone(mockVehicles[0]);return {...v,status:'available' as const,contracts:[],inspections:[],timeline:[],locations:[],mileageKm:1000,rentalContext:{...v.rentalContext,isCurrentlyRented:false,rentalId:undefined}};}
function inspection(type:InspectionRecord['type'],mileage=1000):InspectionRecord{return {id:crypto.randomUUID(),vehicleId:mockVehicles[0].id,rentalId:contract.id,type,date:type==='post_rental'?'2026-01-05T12:00:00Z':'2026-01-01T12:00:00Z',inspectorName:'Inspector',mileage,healthScore:80,condition:{exterior:'good',interior:'clean',tires:'optimal',lights:'all_functional',warningLights:[],fuelLevel:type==='post_rental'?60:90,mileage,healthScore:80,activeFaultsCount:0},notes:'Actual inspection',notesAr:'فحص فعلي',faultsDetected:[]};}
test('contract -> handoff -> return preserves actual mileage and requires release review',()=>{let v=createContract(vehicle(),contract);assert.equal(v.status,'available');v=recordInspection(v,inspection('before_rental'));assert.equal(v.status,'rented');assert.equal(v.rentalContext.isCurrentlyRented,true);v=recordInspection(v,inspection('post_rental',1234));assert.equal(v.status,'inspection');assert.equal(v.mileageKm,1234);assert.equal(v.rentalContext.isCurrentlyRented,false);assert.equal(v.contracts![0].status,'returned');assert.equal(v.timeline[0].rentalId,contract.id);const d=compareRental(v,contract.id);assert.equal(d.distance,234);assert.equal(d.fuelDelta,-30);});
test('rejects overlapping/open rental and bad date range',()=>{const v=createContract(vehicle(),contract);assert.throws(()=>createContract(v,{...contract,id:'TEST-2'}));assert.throws(()=>createContract(vehicle(),{...contract,expectedReturnDate:contract.startDate}));});
test('return without active contract is rejected',()=>assert.throws(()=>recordInspection(vehicle(),inspection('post_rental'))));
test('routine inspection does not rent the vehicle',()=>{const v=recordInspection(vehicle(),{...inspection('routine'),rentalId:undefined});assert.equal(v.status,'available');assert.equal(v.rentalContext.isCurrentlyRented,false);});
test('odometer rollback and invalid fuel rejected',()=>{assert.throws(()=>recordInspection(vehicle(),inspection('routine',900)));const r=inspection('routine');r.condition.fuelLevel=101;assert.throws(()=>recordInspection(vehicle(),r));});
test('comparison never borrows inspections from another contract',()=>{const v=vehicle();v.inspections=[inspection('before_rental'),{...inspection('post_rental',1500),rentalId:'OTHER'}];const d=compareRental(v,contract.id);assert.equal(d.after,undefined);assert.equal(d.distance,null);});
test('new fault and exterior change calculated from same rental',()=>{const v=vehicle();const after=inspection('post_rental',1100);after.faultsDetected=['P0301'];after.condition.exterior='damage_noted';v.inspections=[inspection('before_rental'),after];const d=compareRental(v,contract.id);assert.deepEqual(d.newFaults,['P0301']);assert.equal(d.changes[0].field,'exterior');});
test('GPS import validates, deduplicates and links correct rental',()=>{const v=recordInspection(createContract(vehicle(),contract),inspection('before_rental'));const row={vehicleId:v.id,latitude:24.7,longitude:46.6,timestamp:'2026-01-02T00:00:00Z'};const first=importLocations([v],[row])[0];assert.equal(first.timeline[0].rentalId,contract.id);const second=importLocations([first],[row])[0];assert.equal(second.locations!.length,1);assert.throws(()=>importLocations([v],[{...row,latitude:95}]));assert.throws(()=>importLocations([v],[{...row,vehicleId:'missing'}]));});
test('GPS does not infer a rental outside the contract period',()=>{const v=recordInspection(createContract(vehicle(),contract),inspection('before_rental'));const out=importLocations([v],[{vehicleId:v.id,latitude:24,longitude:46,timestamp:'2025-01-01T00:00:00Z'}])[0];assert.equal(out.timeline[0].rentalId,undefined);});
test('OBD import creates contract-linked faults and threshold alert without marking connection live',()=>{const v=recordInspection(createContract(vehicle(),contract),inspection('before_rental'));v.activeFaults=[];const r={vehicleId:v.id,timestamp:'2026-01-02T10:00:00Z',rpm:900,speed:20,coolantTemp:120,batteryVoltage:13,fuelLevel:50,faultCodes:['P0301']};const out=applyTelemetry(v,r);assert.equal(out.activeFaults[0].code,'P0301');assert.equal(out.timeline[0].rentalId,contract.id);assert.equal(out.sensorData.freshness,'offline');assert.equal(out.earlyWarnings[0].currentValue,'120 °C');assert.throws(()=>applyTelemetry(out,r));const again=applyTelemetry(out,{...r,timestamp:'2026-01-02T11:00:00Z'});assert.equal(again.activeFaults.length,1);assert.equal(again.activeFaults[0].occurrences,2);});
test('CSV escapes quotes, preserves Arabic and protects spreadsheet formulas',()=>{const result=csv([['العقد','x'],['=HYPERLINK("bad")','one,two']]);assert.ok(result.startsWith('\uFEFF'));assert.ok(result.includes("\"'=HYPERLINK"));assert.ok(result.includes('"one,two"'));});
