import {inspectionConditionLabel, inspectionNotes, inspectionErrorMessage} from '../../lib/inspectionLabels';
import React, {useState} from 'react';
import {useApp} from '../../context/AppContext';
import {contractsFor,compareRental} from '../../lib/rental';
import {csv,download,printReport} from '../../lib/export';
import type {Vehicle} from '../../types';

export function RentalWorkspace() {
 const {vehicles,createRental,cancelRental,updateVehicle,setSelectedVehicleId,setIsInspectionModalOpen,isRTL,viewVehicleDetail}=useApp();
 const tr=(ar:string,en:string)=>isRTL?ar:en;
 const [query,setQuery]=useState(''); const [status,setStatus]=useState('all'); const [error,setError]=useState('');
 const [expanded,setExpanded]=useState('');
 const available=vehicles.filter(v=>v.status==='available'&&!contractsFor(v).some(c=>['draft','active'].includes(c.status)));
 const contracts=vehicles.flatMap(v=>contractsFor(v).map(c=>({v,c}))).filter(({v,c})=>(status==='all'||c.status===status)&&`${c.id} ${c.renterName} ${v.plateNumber} ${v.plateNumberAr}`.toLowerCase().includes(query.toLowerCase()));
 const labels:Record<string,string>={draft:tr('بانتظار التسليم','Awaiting handoff'),active:tr('نشط','Active'),returned:tr('مُعاد','Returned'),cancelled:tr('ملغي','Cancelled')};
 const fieldLabels:Record<string,string>={exterior:tr('الهيكل','Exterior'),interior:tr('المقصورة','Interior'),tires:tr('الإطارات','Tires'),lights:tr('الأنوار','Lights')};
 const inspect=(v:Vehicle)=>{setSelectedVehicleId(v.id);setIsInspectionModalOpen(true);};
 const report=(v:Vehicle,id:string,print=false)=>{
  const c=contractsFor(v).find(c=>c.id===id)!;const d=compareRental(v,id);
  const rows:unknown[][]=[[tr('الحقل','Field'),tr('القيمة','Value')],[tr('العقد','Contract'),c.id],[tr('المستأجر','Renter'),c.renterName],[tr('المركبة','Vehicle'),isRTL ? v.plateNumberAr : v.plateNumber],[tr('الفترة','Period'),`${c.startDate} → ${c.expectedReturnDate}`],[tr('الحالة','Status'),labels[c.status]],[tr('فاحص التسليم','Handoff inspector'),d.before?.inspectorName??'—'],[tr('وقت التسليم','Handoff time'),d.before?.date??'—'],[tr('فاحص الإرجاع','Return inspector'),d.after?.inspectorName??'—'],[tr('وقت الإرجاع','Return time'),d.after?.date??'—'],[tr('العداد قبل / بعد','Odometer before / after'),`${d.before?.mileage??'—'} / ${d.after?.mileage??'—'}`],[tr('المسافة كم','Distance km'),d.distance??tr('الفحصان غير مكتملين','Both inspections required')],[tr('الوقود قبل / بعد %','Fuel before / after %'),`${d.before?.condition.fuelLevel??'—'} / ${d.after?.condition.fuelLevel??'—'}`],[tr('تغير الوقود','Fuel change'),d.fuelDelta??'—'],[tr('أكواد جديدة','New codes'),d.newFaults.join(', ')||'—'],[tr('ملاحظات التسليم','Handoff notes'),inspectionNotes(d.before,isRTL)],[tr('ملاحظات الإرجاع','Return notes'),inspectionNotes(d.after,isRTL)],...d.changes.map(x=>[fieldLabels[x.field],`${isRTL ? 'قبل' : 'Before'}: ${inspectionConditionLabel(x.field, x.before, isRTL)} | ${isRTL ? 'بعد' : 'After'}: ${inspectionConditionLabel(x.field, x.after, isRTL)}`]),...d.events.map(e=>[`${e.timestamp||e.date} · ${isRTL?e.titleAr:e.title}`,isRTL?e.descriptionAr:e.description])];
  try {print?printReport(`${isRTL ? 'أثر' : 'Athar'} · ${id}`,rows,isRTL):download(`athar-return-${id.replace(/[^\w-]/g,'_')}.csv`,csv(rows));}catch(e){setError((e as Error).message);}
 };
 return <section className="space-y-5">
  <h2 className="text-2xl font-bold">{tr('العقود وسجل التأجير','Contracts and rental history')}</h2>
  {vehicles.some(v=>v.status==='inspection'&&v.inspections.some(i=>i.type==='routine')&&!contractsFor(v).some(c=>['active','draft'].includes(c.status))) && <details className="bento-card p-5"><summary>{tr('مركبات مفحوصة بانتظار اعتماد الجاهزية','Inspected vehicles awaiting availability review')}</summary>{vehicles.filter(v=>v.status==='inspection'&&v.inspections.some(i=>i.type==='routine')&&!contractsFor(v).some(c=>['active','draft'].includes(c.status))).map(v=><div className="flex flex-wrap gap-3 py-3" key={v.id}><span>{v.make} {v.model} · {v.plateNumber}</span><button className="underline" onClick={()=>viewVehicleDetail(v.id)}>{tr('مراجعة الفحص','Review inspection')}</button><button className="athar-primary" onClick={()=>updateVehicle({...v,status:'available'})}>{tr('اعتماد الجاهزية','Approve availability')}</button></div>)}</details>}
  <details className="bento-card p-5"><summary className="cursor-pointer font-semibold">{tr('إنشاء عقد تأجير','Create rental contract')}</summary>
   <form className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4 mt-5" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{createRental(String(f.get('vehicle')), {id:String(f.get('id')).trim(),renterName:String(f.get('renter')).trim(),startDate:new Date(String(f.get('start'))).toISOString(),expectedReturnDate:new Date(String(f.get('end'))).toISOString(),dailyRate:Number(f.get('rate')),status:'draft'});setError('');e.currentTarget.reset();}catch(err){setError((err as Error).message);}}}>
    <label>{tr('المركبة المتاحة','Available vehicle')}<select name="vehicle" required className="athar-field"><option value="">{tr('اختر مركبة','Select vehicle')}</option>{available.map(v=><option value={v.id} key={v.id}>{v.make} {v.model} · {v.plateNumber}</option>)}</select></label>
    <label>{tr('رقم العقد','Contract ID')}<input name="id" required maxLength={80} className="athar-field"/></label>
    <label>{tr('اسم أو مرجع المستأجر','Renter name or reference')}<input name="renter" required maxLength={120} className="athar-field"/></label>
    <label>{tr('بداية التأجير','Rental start')}<input name="start" type="datetime-local" required className="athar-field"/></label>
    <label>{tr('الإرجاع المتوقع','Expected return')}<input name="end" type="datetime-local" required className="athar-field"/></label>
    <label>{tr('السعر اليومي (ر.س)','Daily rate (SAR)')}<input name="rate" type="number" min="0" step="0.01" required className="athar-field"/></label>
    <button className="athar-primary">{tr('حفظ العقد','Save contract')}</button>
   </form>
  </details>
  {error&&<p role="alert" className="text-red-600">{inspectionErrorMessage(error,isRTL)}</p>}
  <div className="flex gap-3 flex-wrap"><input aria-label={tr('بحث العقود','Search contracts')} className="athar-field sm:max-w-sm" placeholder={tr('ابحث بالعقد أو المستأجر أو اللوحة','Search contract, renter or plate')} value={query} onChange={e=>setQuery(e.target.value)}/><select className="athar-field sm:max-w-xs" aria-label={tr('حالة العقد','Contract status')} value={status} onChange={e=>setStatus(e.target.value)}><option value="all">{tr('كل الحالات','All statuses')}</option>{Object.entries(labels).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></div>
  {!contracts.length&&<p>{tr('لا توجد عقود مطابقة.','No matching contracts.')}</p>}
  <div className="space-y-3">{contracts.map(({v,c})=>{const d=compareRental(v,c.id);return <article key={`${v.id}-${c.id}`} className="bento-card p-5">
   <div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-bold">{c.id} · {c.renterName}</h3><button className="underline text-sm mt-1" onClick={()=>viewVehicleDetail(v.id)}>{v.make} {v.model} · {v.plateNumber}</button><p className="text-sm mt-2">{c.startDate?new Date(c.startDate).toLocaleString(isRTL?'ar-SA':'en-GB'):'—'} → {c.expectedReturnDate?new Date(c.expectedReturnDate).toLocaleString(isRTL?'ar-SA':'en-GB'):'—'}</p><p className="text-sm mt-1">{labels[c.status]} · {c.dailyRate} {tr('ر.س / يوم','SAR / day')}</p></div>
   <div className="flex gap-2 items-start flex-wrap">{['draft','active'].includes(c.status)&&<button className="athar-primary" onClick={()=>inspect(v)}>{c.status==='draft'?tr('فحص وتسليم','Inspect & hand off'):tr('فحص وإرجاع','Inspect & return')}</button>}{c.status==='draft'&&<button className="border rounded-lg p-2 text-sm" onClick={()=>cancelRental(v.id,c.id)}>{tr('إلغاء المسودة','Cancel draft')}</button>}<button className="border rounded-lg p-2 text-sm" onClick={()=>setExpanded(expanded===c.id?'':c.id)}>{tr('السجل والمقارنة','History & comparison')}</button></div></div>
   {expanded===c.id&&<div className="mt-5 pt-5 border-t space-y-4">
    {(!d.before||!d.after)&&<p className="text-amber-700 dark:text-amber-300">{tr('المقارنة تتطلب فحص تسليم وفحص إرجاع للعقد نفسه. لا تُفترض القراءات الناقصة.','Comparison requires handoff and return inspections for this contract. Missing readings are not assumed.')}</p>}
    {d.before&&d.after&&<><div className="grid sm:grid-cols-3 gap-4"><p>{tr('المسافة','Distance')}: <strong>{d.distance} km</strong></p><p>{tr('تغير الوقود','Fuel change')}: <strong>{d.fuelDelta}%</strong></p><p>{tr('أكواد جديدة','New codes')}: <strong>{d.newFaults.join(', ')||tr('لا يوجد','None')}</strong></p></div><ul>{d.changes.map(x => ( <li key={x.field}> <span>{fieldLabels[x.field]}: </span> <span  dir={isRTL ?'rtl' : 'ltr'} className="inline-flex items-center gap-2" > <span>{inspectionConditionLabel(x.field, x.before, isRTL)}</span> <span aria-hidden="true">{isRTL ? '←' : '→'}</span> <span>{inspectionConditionLabel(x.field, x.after, isRTL)}</span> </span> </li> ))}</ul>{!d.changes.length&&<p>{tr('لم تتغير بنود الحالة المسجلة.','No recorded condition fields changed.')}</p>}</>}
    <div className="grid sm:grid-cols-2 gap-4">{[d.before,d.after].map((r,i)=><div key={i}><h4 className="font-semibold">{i===0?tr('فحص التسليم','Handoff inspection'):tr('فحص الإرجاع','Return inspection')}</h4><p className="text-sm">{r?`${r.inspectorName} · ${r.date}`:'—'}</p><p>{inspectionNotes(r,isRTL)}</p><div className="flex flex-wrap gap-2 mt-2">{r?.photos?.map((src,j)=><a key={j} href={src} download={`inspection-${r.id}-${j}.jpg`}><img src={src} alt={tr(`صورة الفحص ${j+1}`,`Inspection photo ${j+1}`)} className="w-24 h-24 object-cover rounded-lg"/></a>)}</div></div>)}</div>
    <p className="text-sm text-neutral-500 dark:text-neutral-400">{tr('تغيّر الحالة أو ظهور عطل لا يثبت مسؤولية المستأجر تلقائياً؛ يلزم مراجعة الفحص والسجل.','A condition change or fault does not automatically establish renter responsibility; review the inspections and history.')}</p>
    <ol className="space-y-2">{d.events.map(e=><li key={e.id} className="border-s-2 border-emerald-600 ps-3"><p className="font-semibold">{isRTL?e.titleAr:e.title}</p><p className="text-sm">{e.timestamp||`${e.date} ${e.time}`} · {isRTL?e.descriptionAr:e.description}</p></li>)}</ol>
    {c.status==='active'&&<form className="flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const text=String(f.get('note')).trim();if(!text)return;const now=new Date().toISOString();updateVehicle({...v,timeline:[{id:crypto.randomUUID(),rentalId:c.id,type:'fault_detected',timestamp:now,date:now.slice(0,10),time:now.slice(11,16),title:'Manual mechanical observation',titleAr:'ملاحظة فنية يدوية',description:text,descriptionAr:text},...v.timeline]});e.currentTarget.reset();}}><label className="flex-1">{tr('ملاحظة فنية أثناء التأجير','Mechanical observation during rental')}<input className="athar-field" name="note" required maxLength={1000}/></label><button className="athar-primary self-end">{tr('إضافة للسجل','Add to history')}</button></form>}
    <div className="flex flex-wrap gap-3"><button className="athar-primary" onClick={()=>report(v,c.id)}>{tr('تنزيل تقرير CSV','Download CSV report')}</button><button className="border rounded-lg p-2" onClick={()=>report(v,c.id,true)}>{tr('طباعة / حفظ PDF','Print / Save PDF')}</button>{c.status==='returned'&&v.status==='inspection'&&!contractsFor(v).some(x=>['draft','active'].includes(x.status))&&<><button className="border rounded-lg p-2" onClick={()=>updateVehicle({...v,status:'available'})}>{tr('اعتماد جاهزية المركبة','Approve vehicle availability')}</button><button className="border rounded-lg p-2" onClick={()=>updateVehicle({...v,status:'maintenance'})}>{tr('تحتاج صيانة','Requires maintenance')}</button></>}</div>
   </div>}
  </article>})}</div>
 </section>;
}
